=== a24yaniravc/LMSXI_UNIDAD4/DTD/ex15/order.dtd
<!ELEMENT order (tractor+)>
<!ELEMENT tractor (component+)>
<!ELEMENT component (delivery_date?, weight, serial_number, max_km)>
<!ATTLIST component manufacturer_name CDATA #REQUIRED>
<!ATTLIST component fragile (yes | no) #REQUIRED>
<!ELEMENT serial_number (#PCDATA)>
<!ELEMENT delivery_date (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight unit (kilos | grams) #REQUIRED>
<!ELEMENT max_km (#PCDATA)>

=== a24yaniravc/LMSXI_UNIDAD4/DTD/ex15/order.xml
<!DOCTYPE order SYSTEM "order.dtd">

<order>
    <tractor>
        <component manufacturer_name="Juanjo's Tools" fragile="no">
            <delivery_date>2010-10-02</delivery_date>
            <weight unit="kilos">10</weight>
            <serial_number>12345678</serial_number>
            <max_km></max_km>
        </component>
        <component manufacturer_name="Pepe's tools" fragile="yes">
            <weight unit="grams">50</weight>
        </component>
    </tractor>
    <tractor>
        <component manufacturer_name="Pepe's tools" fragile="yes">  
            <delivery_date>2010-10</delivery_date>
            <weight unit="grams">20</weight>
            <serial_number>12341234</serial_number>
            <max_km>20</max_km>
        </component>
    </tractor>
</order>
