<?xml version="1.0"?>	
<!DOCTYPE stock[	
<!ELEMENT stock (new-car|used-car)*>	
<!ELEMENT new-car (model,price)>	
<!ELEMENT used-car (model,price,mileage,condition?)>	
<!ELEMENT model (#PCDATA)>	
<!ELEMENT price (#PCDATA)>	
<!ELEMENT mileage (#PCDATA)>	
<!ELEMENT condition (#PCDATA)>	
]>

<stock>
    <new-car>
        <model>SEAT LEON</model>
        <price>30,000€</price>
    </new-car>
    <used-car>
        <model>PEUGEOT 3008</model>
        <price>20,000€</price>
        <mileage>100,000km</mileage>
        <condition>Good</condition>
    </used-car>
    <used-car>
        <model>RENAULT QASHQAI</model>
        <price>50,000€</price>
        <mileage>40,000km</mileage>
    </used-car>
</stock>